### ISSUE TITLE
Firefox ServiceNow Pluggin Not Working properly

### ISSUE THREAD

**Issue by Kaustubh3** [sekarpdkt/servicenow-audio-alert-chrome-extension#1]
1. The Service now audio alerts are not syncing properly with the flow of tickets.
2. Every time a new ticket comes it does not give audio alert until we save the extension settings manually.
3.We tried with different filters,however, it only worked on few.
4. For more updates you can reach out to me on +918208503496

**Comment by sekarpdkt** [comment]
Try the latest version in Google Chrome. Following enhancements are implemented.

in sometimes will be uploading some new feature
1. You can disable alarm
2. You can disable poll
3. You can enable alarm on either >0 count or new ticket to that monitored queue
4. You can also change poll time interval.

Primarily, it will work based on new tickets coming to a queue with state as new. If due to some different enhanced processes,  if the new ticket is coming in different state (or directly in In-progress due to system self diagnosis), you may need to tweak the queue filter. So, the option of enabling alert of new ticket to queue might be of use, instead of default count>0.

**Comment by sekarpdkt** [comment]
It shall work with new update as new update uses rest API instead of XML API. Also option added to alert based on count or new incident in the queue.
