### ISSUE TITLE
Its not working

### ISSUE THREAD

**Issue by nileshpatil1984** [sekarpdkt/servicenow-audio-alert-chrome-extension#2]
Firstly Thank you for efforts , this will surely help for tracking and achive the timeline in customer updates 👍  i have seen issues post the implemention.
1) Configuration done for Service now audio alerts , but i have not received any alerts once new case received. 
2) Configuration is done on two system, another systeam getting alerts but not for all new cases , notifications are random not accurate.
3) Notification timers are not constant sometime getting alert in 15 minute sometime in more than 30 minutes that too not for all cases.
4) Can we modify the notification timers ? 

Please look in to reported issues and suggest if any systeam level tweaking is needed or any scope to develop.

Regards,
Nilesh Patil
+91 89836 99777

**Comment by sekarpdkt** [comment]
Try the latest version in Google Chrome. Following enhancements are implemented.

in sometimes will be uploading some new feature
1. You can disable alarm
2. You can disable poll
3. You can enable alarm on either >0 count or new ticket to that monitored queue
4. You can also change poll time interval.

Primarily, it will work based on new tickets coming to a queue with state as new. If due to some different enhanced processes,  if the new ticket is coming in different state (or directly in In-progress due to system self diagnosis), you may need to tweak the queue filter. So, the option of enabling alert of new ticket to queue might be of use, instead of default count>0.

**Comment by sekarpdkt** [comment]
It shall work with new update as new update uses rest API instead of XML API. Also option added to alert based on count or new incident in the queue.
